# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 06:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20170622_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='borrower',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL),
        ),
    ]
